# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('width', models.PositiveIntegerField(verbose_name='Ancho')),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='layout.Block')),
            ],
            options={
                'verbose_name': 'Columna',
                'verbose_name_plural': 'Columnas',
            },
        ),
        migrations.CreateModel(
            name='ContentElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('content_type', models.CharField(choices=[('ADV', 'Publicidad'), ('ART', 'Articulo Grande'), ('THU', 'Articulo Pequeño'), ('CAR', 'Carrusel'), ('CUS', 'Personalizado')], max_length=3, verbose_name='Tipo de Contenido')),
                ('html_code', models.TextField(blank=True, null=True, verbose_name='Contenido Personalizado')),
                ('advertising', models.ImageField(blank=True, null=True, upload_to='images/advertising', verbose_name='Imagen de Publicidad')),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='layout.Column')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
            },
        ),
    ]
